# Generated by Django 2.2.15 on 2020-08-13 07:16

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False, verbose_name='ID')),
                ('lang', models.SmallIntegerField(choices=[(1, '中文'), (2, '英文')], default=1, verbose_name='语言')),
                ('content', tinymce.models.HTMLField(default='', verbose_name='正文内容')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('modify_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
            ],
            options={
                'verbose_name': '关于网站',
                'verbose_name_plural': '关于网站',
                'ordering': ['-id'],
            },
        ),
    ]
