# Generated by Django 2.2.12 on 2020-05-08 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='enable',
            field=models.BooleanField(default=False, help_text='是否发布可见，默认不发布可见，一般在文章编辑完成后再发布可见', verbose_name='发布状态'),
        ),
        migrations.AddField(
            model_name='publication',
            name='enable',
            field=models.BooleanField(default=False, help_text='是否发布可见，默认不发布可见，一般在文章编辑完成后再发布可见', verbose_name='发布状态'),
        ),
    ]
